"use client";

import { useCallback, useState } from "react";

// The master switch for printing Monday's Trims entries on cover pages.
//
// It exists because turning this on changes what every cover in the book says
// to a supplier, and that is a decision worth taking deliberately — with other
// people's eyes on a real page first. So the feature shipped dark: everything
// around it works while this is off (the rules are editable, the before/after
// preview renders, the single-style PDF check renders), and the only thing the
// switch controls is whether a cover that gets WRITTEN carries the trims.
//
// Turning it on does not rebuild anything by itself. Existing covers keep what
// they have until they are regenerated; new generations pick it up immediately.

export function TrimsSwitch({ initialEnabled }: { initialEnabled: boolean }) {
  const [enabled, setEnabled] = useState(initialEnabled);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const toggle = useCallback(
    async (next: boolean) => {
      setSaving(true);
      setError(null);
      // Optimistic, then reverted on failure — the control has to feel like a
      // switch, but must never show "on" when the server says otherwise.
      setEnabled(next);
      try {
        const res = await fetch("/api/admin/settings/cover-page/trims-switch", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ enabled: next }),
        });
        if (!res.ok) {
          throw new Error((await res.json().catch(() => null))?.error ?? `Failed (${res.status})`);
        }
      } catch (e) {
        setEnabled(!next);
        setError(e instanceof Error ? e.message : "Could not save");
      } finally {
        setSaving(false);
      }
    },
    [],
  );

  return (
    <div className="mt-10 rounded-lg border border-zinc-200 bg-white p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-sm font-semibold text-zinc-800">
            Print the Monday Trims list on cover pages
          </h2>
          <p className="mt-1 max-w-2xl text-[13px] leading-relaxed text-zinc-500">
            Off: a cover lists only the documents this app produces — exactly as it always has.
            On: it lists every entry from the style&rsquo;s Monday <strong>Trims</strong> column in
            Monday&rsquo;s own words, marked as generated by us, supplied separately, or a packing
            instruction with no artwork.
          </p>
          <p className="mt-2 max-w-2xl text-[13px] leading-relaxed text-zinc-500">
            Turning this on does not change any existing cover on its own. Newly generated bundles
            pick it up straight away; the covers already in suppliers&rsquo; folders keep what they
            have until you rebuild them from the panel above.
          </p>
        </div>
        <label className="flex shrink-0 cursor-pointer items-center gap-2">
          <input
            type="checkbox"
            checked={enabled}
            disabled={saving}
            onChange={(e) => toggle(e.target.checked)}
            className="h-4 w-4"
          />
          <span className={`text-sm font-medium ${enabled ? "text-emerald-700" : "text-zinc-500"}`}>
            {enabled ? "On" : "Off"}
          </span>
        </label>
      </div>

      {error && (
        <div className="mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-[13px] text-red-700">
          {error}
        </div>
      )}

      {!enabled && (
        <p className="mt-3 rounded-md border border-sky-200 bg-sky-50 px-3 py-2 text-[13px] text-sky-900">
          While this is off you can still agree the vocabulary on{" "}
          <strong>Settings &rarr; Trims</strong>, read the before/after above, and open a real cover
          PDF for any style number. Nothing a supplier sees changes until you switch it on.
        </p>
      )}
    </div>
  );
}
